// <auto-generated />
using System;
using GerenciadorFinanca.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GerenciadorFinanca.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20221110154306_atualizacaofinalfk")]
    partial class atualizacaofinalfk
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GerenciadorFinanca.Models.Despesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("DespFK")
                        .HasColumnType("int");

                    b.Property<DateTime>("DespesaData")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NomeDespesa")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal 10,2(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("DespFK");

                    b.ToTable("Despesas");
                });

            modelBuilder.Entity("GerenciadorFinanca.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GerenciadorFinanca.Models.Despesa", b =>
                {
                    b.HasOne("GerenciadorFinanca.Models.Usuario", "Usuario")
                        .WithMany("Despesas")
                        .HasForeignKey("DespFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GerenciadorFinanca.Models.Usuario", b =>
                {
                    b.Navigation("Despesas");
                });
#pragma warning restore 612, 618
        }
    }
}
