// <auto-generated />
using System;
using GerenciadorFinanca.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GerenciadorFinanca.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20221110143223_chavefk")]
    partial class chavefk
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GerenciadorFinanca.Models.Despesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DespesaData")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NomeDespesa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Despesas");
                });

            modelBuilder.Entity("GerenciadorFinanca.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("despesaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("despesaId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GerenciadorFinanca.Models.Usuario", b =>
                {
                    b.HasOne("GerenciadorFinanca.Models.Despesa", "despesa")
                        .WithMany()
                        .HasForeignKey("despesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("despesa");
                });
#pragma warning restore 612, 618
        }
    }
}
